<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kiara Ardina_05385688-ba91-424e-92cf-_9373e1</name>
   <tag></tag>
   <elementGuidId>065e529f-9449-4420-9434-b8288c7c4659</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='05385688-ba91-424e-92cf-4bec0e9c9e3c']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;05385688-ba91-424e-92cf-4bec0e9c9e3c&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>05385688-ba91-424e-92cf-4bec0e9c9e3c</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-checkbox-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout ant-layout-has-sider tw-w-screen&quot;]/section[@class=&quot;ant-layout tw-bg-white&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-pt-28 tw-px-28 remove-content&quot;]/div[@class=&quot;ant-card ant-card-bordered tw-rounded-lg tw-space-y-3 tw-mt-5&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;ant-list ant-list-split&quot;]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/ul[@class=&quot;ant-list-items&quot;]/li[@class=&quot;ant-list-item tw-flex tw-whitespace-nowrap select-agency&quot;]/div[@class=&quot;ant-list-item-meta&quot;]/div[@class=&quot;ant-list-item-meta-content&quot;]/h4[@class=&quot;ant-list-item-meta-title&quot;]/div[@class=&quot;tw-flex signup tw-flex-row tw-justify-between tw-whitespace-nowrap&quot;]/label[@class=&quot;ant-checkbox-wrapper&quot;]/span[@class=&quot;ant-checkbox&quot;]/input[@class=&quot;ant-checkbox-input&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='05385688-ba91-424e-92cf-4bec0e9c9e3c']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/main/div/div[4]/div/div/div/div/ul/li/div/div/h4/div/label/span/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span/input</value>
   </webElementXpaths>
</WebElementEntity>
