<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Create Remarketing Exercise</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>50579af4-800a-40e9-90c2-fe71ea1ce177</testSuiteGuid>
   <testCaseLink>
      <guid>876ea381-c3b6-44a1-b9d9-b6fa23f546bd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Agent/Remarketing exercise/tc_01_FilledAllFieldCorrectly</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39f2e046-076d-40d4-a670-25852222cd09</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8b7c65a-f1bb-4716-ab6b-93a5a4c13d3d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0c2e6f24-1366-4d18-bfc6-0eb036d69379</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Agent/Remarketing exercise/tc_02_ChoosingExistingPolicyMoreThanOne</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>379c6d9d-dde8-4542-a231-c9b78120f168</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9dbe4b0e-82b6-4a17-a5c4-fe1dbc3b39bb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ef0a3d07-c081-4af8-a5e7-0b776b31d2c8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Agent/Remarketing exercise/tc_03_EmptyExerciseName</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dba1718a-4dfb-4de9-9071-7e7f6e9b76c8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c7872163-066e-468b-9f79-9b51dffa348c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Agent/Remarketing exercise/tc_04_EmptyRenewalPeriod</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e2d119e-afb3-48d1-9894-7cd3d9ab2735</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b0966d64-9e48-4318-b0e0-8647da0f7c83</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Agent/Remarketing exercise/tc_05_EmptyPlanDesign</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2edb446c-f05c-464e-9788-a7b8e0a4a5c9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8fe4d586-a2ef-49fc-ab4c-d31a316d55e0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Agent/Remarketing exercise/tc_06_AddExistingPolicy</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3fd9c48-2d89-4c17-9b7b-580a7ab03dd2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d69c00e5-7135-4f5e-b216-969c214a881c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Agent/Remarketing exercise/tc_07_EmptyEmployeeList</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>655f8faf-f121-4728-af5a-c5082ff47e3a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>24d2fd41-c1f6-492b-9407-ad92c51b11dd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Agent/Remarketing exercise/tc_08_ChoosePackagePlanMoreThanOne</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b7f2bda-0d94-46aa-af00-b6bc11e06890</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cf7a9c73-2058-4b51-a7c0-c04e2b13bdc0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Agent/Remarketing exercise/tc_09_DeleteExistingPolicy</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e86e216a-8b9c-47a7-a054-2e7c5eb4b356</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c85cef90-9b14-4429-a7fa-da78b5953799</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Agent/Remarketing exercise/tc_10_FilledExistingPolicyMoreThan1WithoutSelectPlan</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e38b323b-0573-4ca3-8b5c-090d76711b0a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Agent/Remarketing exercise/tc_11_Upload Employee</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfb9607c-9328-4b91-9419-5d18202242d7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5c3321f8-9f1b-422f-b167-deb195abd32d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Agent/Remarketing exercise/tc_12_Invalid Date</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02c869ba-e413-411a-9a52-374710245afe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6f43dff-f42b-4eca-82e4-761894196959</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dfbcfd9c-979a-4dc5-b139-a99075e2258b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Agent/Remarketing exercise/tc_13_Back to Previous Page</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32462483-cba2-424c-b248-58224266a9b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66228663-b0fa-43ea-94da-95720ffd6dca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2df18fa8-53cc-4e35-8fd4-d220474a99cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Agent/Remarketing exercise/tc_14_Using Search button</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>146d6080-248e-48d1-a654-1a1b6642e1a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfcc3eff-e779-4a2c-84b9-b4e56384541f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ea1f5ab6-854e-4710-9596-5868e63367bf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Agent/Remarketing exercise/tc_15_Generate Quotation Slip</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a65aed2a-fc6a-420a-ba47-22fc13e0d511</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58cea987-5f7d-4eca-be11-7ad3277623d5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8ba47a80-37ef-4537-a660-27939eac9fa5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Agent/Remarketing exercise/tc_16_Send Quotation Slip</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b635422f-60f9-4c45-8141-87fce5018bc3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b6e622a-2a16-42ae-8664-3a444220513c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8844afd9-236b-46df-a236-b08e1606815b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Agent/Remarketing exercise/tc_17_Send Quotation Slip and Generate before select package plan</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63e198af-3408-4efb-b208-8a77ff28cc76</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09a81b75-e3fb-469e-b945-f7722a7f2c8e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>da8ae20d-0c00-4b70-97ce-e1f8abaf5751</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Agent/Remarketing exercise/tc_18_Save as Draft</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7229ec04-bc25-4f39-940d-609d50c525ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c732c8d-5ff8-4063-8526-69a96c36925a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
