<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Update Agency</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>e9bbe24d-887c-41a6-a10d-09d42eb563ab</testSuiteGuid>
   <testCaseLink>
      <guid>45a21cec-28d1-4ca3-8223-cfe41b3f68b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Admin/UpdateAgency/UpdatingFieldOnAgency</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e84eb30f-fc76-43c5-a58c-9a42b63ab38f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>231f3437-3dca-4749-9424-991d49f4d05a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7649ec70-518c-46a2-b4a2-65ba929ba533</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67299452-85c9-4a11-b3cd-21b5ba666afa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>357bda74-b6c1-44c7-874c-2d8e85642169</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4db7ee3d-202c-4c43-925b-2878f182c265</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Admin/UpdateAgency/UpdatingFieldOnAgencyWithNoChange</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee1093fd-9c26-46ea-897e-5ede8985add0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be98bc35-0e2f-4fd0-bc63-3a7888961742</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4eb5747a-9871-45bd-913a-b28106832709</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b15a104-65df-4fd3-945b-3a2803d648bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ca75974-d28c-4184-bba3-df32c9c7af77</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>95c73fcb-b490-472c-884b-4d413b3fa3ba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Admin/UpdateAgency/UpdatingFieldOnAgencyWithEmptyField</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c092ab37-68aa-46c9-a775-c5e2b3d4c11e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94d7073c-a04d-489a-94de-8859b94a7c51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4973d0e-64b4-42f7-a399-bb102bc6fb10</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1858d00d-61a7-4cff-aa40-c3bbf0ce28c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9042d2bc-63ec-45ed-b9f6-bc725f46103b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
