<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Update Policy</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>e2d87717-1083-463b-93de-5bb8ee7a95b1</testSuiteGuid>
   <testCaseLink>
      <guid>b793568b-1959-4ef6-bf63-87d364761372</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Admin/Update Policy/Update_Policy</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65433e0d-9872-4149-8ed3-e777742e7282</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91692405-d9f6-4dc0-bec0-23649ad6d3a7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>515c3203-2e32-4fdf-bd39-c658712e5a6f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Admin/Update Policy/Update_Policy With No Change</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6af9cc3f-8969-466d-abd8-a3495071913c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>989aefbf-69b4-43a3-95bf-1620266fe1ff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>74ffb905-cd03-4ee1-9a16-236502603c29</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Admin/Update Policy/Update_Policy Using Search Button On Insurer Section</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b270be6a-07d2-4f1d-b46a-efd7c8b344cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac038560-eaec-4020-a546-9fe173813024</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
