<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Unique_Policy Type Chosen 1</name>
   <tag></tag>
   <elementGuidId>6cf0a940-9510-49a5-99d1-8ab36259cf32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/div/div[2]/div[2]/div/div[4]/div/div[1]/div/button[1]/span/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reverse-checkbox-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>existingPolicy</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reverse-checkbox-0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>{&quot;id&quot;:939,&quot;insuranceId&quot;:null,&quot;policy&quot;:null,&quot;startingPolicy&quot;:null,&quot;endingPolicy&quot;:null,&quot;quotationId&quot;:null,&quot;remarketingExerciseId&quot;:null,&quot;customerId&quot;:540,&quot;eligibility&quot;:null,&quot;poolingNetwork&quot;:null,&quot;eligibilityDate&quot;:null,&quot;maxAgeOfCovered&quot;:null,&quot;policyAdministration&quot;:null,&quot;experienceRefund&quot;:null,&quot;productRatedWith&quot;:null,&quot;policyHolderRatedTogether&quot;:null,&quot;eUnderwriting&quot;:null,&quot;letterOfGuaranteeFacility&quot;:null,&quot;claimReimbursementViaDirect&quot;:null,&quot;comissionRate&quot;:null,&quot;minimumConfinement&quot;:null,&quot;keyExclusion&quot;:null,&quot;specialTerms&quot;:null,&quot;comments&quot;:null,&quot;groupInsuranceId&quot;:35,&quot;packagePlanId&quot;:null,&quot;createdAt&quot;:&quot;2022-11-22T00:54:54.000Z&quot;,&quot;updatedAt&quot;:&quot;2022-11-24T05:42:59.000Z&quot;,&quot;deletedAt&quot;:null,&quot;PremiumRates&quot;:[],&quot;BenefitPlans&quot;:[],&quot;BasisCovers&quot;:[],&quot;GroupInsurance&quot;:{&quot;id&quot;:35,&quot;name&quot;:&quot;Health policy&quot;,&quot;description&quot;:&quot;general policy&quot;,&quot;licenseType&quot;:&quot;Life&quot;,&quot;createdAt&quot;:&quot;2022-11-08T03:18:29.000Z&quot;,&quot;updatedAt&quot;:&quot;2022-11-08T03:21:45.000Z&quot;,&quot;deletedAt&quot;:null},&quot;Insurance&quot;:null}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reverse-checkbox-0&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reverse-checkbox-0']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/div[3]/form/div[3]/div/div[2]/div[2]/form/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
