<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Unique_choosing package plan2</name>
   <tag></tag>
   <elementGuidId>67681359-78cd-4fa0-a203-0234dd79470f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/div/div[2]/div[2]/div/div[4]/div/div[2]/div[2]/div/button/span/div/div[3]
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ant-checkbox-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-checkbox-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;tw-flex tw-bg-greyBg&quot;]/div[2]/div[@class=&quot;custome-steps&quot;]/div[4]/div[@class=&quot;tw-mt-5 tw-flex tw-flex-col tw-space-y-5&quot;]/div[@class=&quot;tw-bg-white tw-rounded-lg tw-p-5 tw-h-auto tw-flex tw-flex-col tw-justify-between&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-space-y-3 tw-pl-2 custome-input-icon&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-space-y-3 custome-card tw-overflow-y-auto tw-h-80&quot;]/div[@class=&quot;ant-card ant-card-bordered  tw-border-2 tw-h-16 tw-rounded-lg&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;tw-flex tw-flex-row tw-justify-between&quot;]/div[@class=&quot;tw-flex tw-flex-row tw-space-x-2&quot;]/div[@class=&quot;tw-pt-2 tw-pl-3 custome-checkbox-package&quot;]/label[@class=&quot;ant-checkbox-wrapper&quot;]/span[@class=&quot;ant-checkbox&quot;]/input[@class=&quot;ant-checkbox-input&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div/div[4]/div/div[2]/div[2]/div/div/div/div/div[2]/div[2]/label/span/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span/input</value>
   </webElementXpaths>
</WebElementEntity>
