<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_insurer wording2</name>
   <tag></tag>
   <elementGuidId>807394c5-0838-4568-84f0-68fca312f070</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;e80fe58d-64a2-4edd-a0bc-5ed8a688b5fb&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;control-ref&quot;]/div[3]/div/div[2]/div/div/div/div/ul/li[3]/div/div/h4/div/label/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>e80fe58d-64a2-4edd-a0bc-5ed8a688b5fb</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-checkbox-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;control-ref&quot;)/div[@class=&quot;tw-w-full tw-flex tw-flex-col tw-bg-white tw-p-6 tw-rounded-lg tw-space-y-5 tw-mt-5&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-space-y-5&quot;]/div[@class=&quot;ant-card ant-card-bordered tw-rounded-lg form-policy-affected tw-space-y-5 tw-mt-5&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;ant-list ant-list-split&quot;]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/ul[@class=&quot;ant-list-items&quot;]/li[@class=&quot;ant-list-item&quot;]/div[@class=&quot;ant-list-item-meta&quot;]/div[@class=&quot;ant-list-item-meta-content&quot;]/h4[@class=&quot;ant-list-item-meta-title&quot;]/div[@class=&quot;tw-flex tw-flex-row tw-justify-between&quot;]/label[@class=&quot;ant-checkbox-wrapper&quot;]/span[@class=&quot;ant-checkbox&quot;]/input[@class=&quot;ant-checkbox-input&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='e80fe58d-64a2-4edd-a0bc-5ed8a688b5fb']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='control-ref']/div[3]/div/div[2]/div/div/div/div/ul/li/div/div/h4/div/label/span/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/div/ul/li/div/div/h4/div/label/span/input</value>
   </webElementXpaths>
</WebElementEntity>
